### ISSUE TITLE
Dashboards are not getting deployed on Windows

### ISSUE THREAD

**Issue by tusharkapadi** [Appdynamics/FastAppConfig#8]
I downloaded FastAppConfig on Windows 2012 R2 Ravello machine. FastAppConfig app runs fine, I am able to update the settings and connect to the controller fine. It fetches the list of dashboards and applications fine. When I deploy any dashboard, it says 'successfully deployed', but I don't see any dashboard on the controller.

Controller is running on ubuntu (Ravello)
FastAppConfig is running on Windows 2012 R2 (Ravello)
Generating load from my local machine pointing to the controller.

Deploying Dashboard using FastAppConfig
<img width="1097" alt="deploying_dashboard" src="https://cloud.githubusercontent.com/assets/13192655/22991371/dc18b9aa-f370-11e6-858f-286011d7ad90.png">

Don't see Dashboard on the controller
<img width="1095" alt="no_dashboard" src="https://cloud.githubusercontent.com/assets/13192655/22991377/dfa035e4-f370-11e6-9f53-e351187f314b.png">

**Comment by jdbarfield** [comment]
Tushar. This is working for me in Windows. Please include the controller version and the dashboard name. 

Also, it might help to consult the log files on the controller machine to see why a dashboard isn't getting imported. This can be found at:

<controller_dir>\appserver\glassfish\domains\domain1\bin\AppDynamicsDomain1Service.err.log

**Comment by rijincp** [comment]
@tusharkapadi , This seem to be working. I am closing this. Please reopen with more info if the issue persists. Thanks.
